Improve icons handling in tui and webapps

diff --git a/bin/omakub-tui-install b/bin/omakub-tui-install
--- a/bin/omakub-tui-install
+++ b/bin/omakub-tui-install
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-if [ "$#" -ne 4 ]; then
+f [ "$#" -ne 4 ]; then
   echo -e "\e[32mLet's create a TUI shortcut you can start with the app launcher.\n\e[0m"
   APP_NAME=$(gum input --prompt "Name> " --placeholder "My TUI")
   APP_EXEC=$(gum input --prompt "Launch Command> " --placeholder "lazydocker or bash -c 'dust; read -n 1 -s'")
@@ -20,13 +20,16 @@ fi
 
 ICON_DIR="$HOME/.local/share/applications/icons"
 DESKTOP_FILE="$HOME/.local/share/applications/$APP_NAME.desktop"
-ICON_PATH="$ICON_DIR/$APP_NAME.png"
 
-mkdir -p "$ICON_DIR"
-
-if ! curl -sL -o "$ICON_PATH" "$ICON_URL"; then
-  echo "Error: Failed to download icon."
-  return 1
+if [[ ! "$ICON_URL" =~ ^https?:// ]] && [ -f "$ICON_URL" ]; then
+  ICON_PATH="$ICON_URL"
+else
+  ICON_PATH="$ICON_DIR/$APP_NAME.png"
+  mkdir -p "$ICON_DIR"
+  if ! curl -sL -o "$ICON_PATH" "$ICON_URL"; then
+    echo "Error: Failed to download icon."
+    exit 1
+  fi
 fi
 
 if [[ $WINDOW_STYLE == "float" ]]; then
@@ -40,7 +43,7 @@ cat >"$DESKTOP_FILE" <<EOF
 Version=1.0
 Name=$APP_NAME
 Comment=$APP_NAME
-Exec=alacritty --class $APP_CLASS -e $APP_EXEC
+Exec=$TERMINAL --class $APP_CLASS -e $APP_EXEC
 Terminal=false
 Type=Application
 Icon=$ICON_PATH
