Enhance Gnome ext update script

diff --git a/bin/omakub-update-gnome-extensions b/bin/omakub-update-gnome-extensions
--- a/bin/omakub-update-gnome-extensions
+++ b/bin/omakub-update-gnome-extensions
@@ -1,14 +1,16 @@
 #!/bin/bash
 
 # Check if there are updates available for GNOME extensions
-if gext update --dry-run &>/dev/null; then
-  exit_code=$?
+echo -e "\e[32m\nUpdate GNOME extensions\e[0m"
 
-  # Exit code 17 means updates are available
-  if [ $exit_code -eq 17 ]; then
-    echo "Updating GNOME extensions..."
-    gext update --yes
-    omakub-state set logout-required
-  fi
+gext update --dry-run &>/dev/null
+exit_code=$?
+
+# Exit code 17 means updates are available
+if [ $exit_code -eq 17 ]; then
+  gext update --yes
+  omakub-state set logout-required
+else
+  echo -e "Already up to date."
 fi
 
