Add Omarchy v3 configs & commands

diff --git a/default/bash/aliases b/default/bash/aliases
--- a/default/bash/aliases
+++ b/default/bash/aliases
@@ -11,7 +11,7 @@ zd() {
   elif [ -d "$1" ]; then
     builtin cd "$1"
   else
-    z "$@" && printf " \U000F17A9 " && pwd || echo "Error: Directory not found"
+    z "$@" && printf "\U000F17A9 " && pwd || echo "Error: Directory not found"
   fi
 }
 
@@ -23,6 +23,7 @@ alias ....='cd ../../..'
 # Tools
 alias g='git'
 alias d='docker'
+alias r='rails'
 alias bat='batcat'
 alias lzg='lazygit'
 alias lzd='lazydocker'
@@ -34,6 +35,7 @@ open() {
 }
 
 # Git
+alias g='git'
 alias gcm='git commit -m'
 alias gcam='git commit -a -m'
 alias gcad='git commit -a --amend'
